---
verifyConditions:
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"

publish:
  - "@semantic-release/npm"
  - "@semantic-release/github"

prepare:
  - "@semantic-release/npm"
  - "@semantic-release/git"

branch: "v5"
